### ISSUE TITLE
Where does index.html come from?

### ISSUE THREAD

**Issue by ablakey** [pbarbiero/basic-electron-react-boilerplate#10]
Forgive my ignorance but I'm trying to reverse this boilerplate to better understand what's going on. 

Where does `index.html` come from?

I'm not new to React but am pretty new to Electron, so maybe there's some magic I'm not aware of?

**Comment by pbarbiero** [comment]
That comes from the webpack plugin `html-webpack-plugin` -- nothing to do with Electron.
