### ISSUE TITLE
HMR not wokring.

### ISSUE THREAD

**Issue by akshaygarg834** [pbarbiero/basic-electron-react-boilerplate#4]
Try change anything in App.js file. It will show a warning in console (in electron window).

// dev-server.js:34 [HMR] Error: Aborted because 140 is not accepted
// Update propagation: 140 -> 139 -> 134 -> 307
//     at hotApply (http://localhost:8080/bundle.js:430:30)
//     at hotUpdateDownloaded (http://localhost:8080/bundle.js:283:13)
//     at hotAddUpdateChunk (http://localhost:8080/bundle.js:263:13)
//     at webpackHotUpdateCallback (http://localhost:8080/bundle.js:8:12)
//     at http://localhost:8080/0.1d5e6bcfd13ee4889dc2.hot-update.js:1:1
// (anonymous) @ dev-server.js:34

**Comment by pbarbiero** [comment]
You need to set up your app yourself to accept HMR. Webpack is only configured to enable it. See https://webpack.js.org/guides/hmr-react/ for more info.
