### ISSUE TITLE
Cannot load synchronize/node-fibers

### ISSUE THREAD

**Issue by CiriousJoker** [pbarbiero/basic-electron-react-boilerplate#8]
When I try to load node-fibers, it throws:

> Uncaught Error: Module parse failed: D:\Projects\C#\LegacyManagerBoilerplate2\node_modules\fibers\fibers.js 'return' outside of function (2:1)
You may need an appropriate loader to handle this file type.
| if (process.fiberLib) {
| 	return module.exports = process.fiberLib;
| }
| var fs = require('fs'), path = require('path');
    at Object.<anonymous> (bundle.js:59785)
    at __webpack_require__ (bundle.js:660)
    at fn (bundle.js:86)
    at Object.<anonymous> (bundle.js:13715)
    at __webpack_require__ (bundle.js:660)
    at fn (bundle.js:86)
    at Object.<anonymous> (bundle.js:30213)
    at __webpack_require__ (bundle.js:660)
    at fn (bundle.js:86)
    at Object.exports.__esModule (bundle.js:54167)

I have tried a lot, but I nothing seems to work. Do you have any ideas on why this doesn't work?

**Comment by CiriousJoker** [comment]
This seems to happen because Webpack fucks with __dirname and therefore a bunch of modules can't load.

Adding

```
externals: {
 fibers: "commonjs fibers"
},
```

to the build configs works. Don't have time to make a pull request though, sorry.

**Comment by pbarbiero** [comment]
Yeah this is a pretty common issue when working with electron, webpack with modules meant for node. Webpack configures the common and internal node libraries with the externals value (with the `target: electron` configuration line) but any you add yourself you'll need to handle as you've discovered.

This isnt a bug with anything, its just environment configuration. Typically code like that you should throw into the electron side, not the renderer side and that would avoid bumping into this but theres no problems doing what your doing.

You'll bump into this again I am sure, but now you know how to fix it 🎉 

No need for a pull request, this doesn't belong in the boilerplate but I appreciate the issue to help others find this answer in the future.
