### ISSUE TITLE
Build not working

### ISSUE THREAD

**Issue by ognjetina** [pbarbiero/basic-electron-react-boilerplate#9]
Hi after I run
```npm run package```
It completed building but after I start electron from builds/ it opens an empty electron...
If I pull index.html page in it than the app works.

Is something wrong with packager or I am not using it right?

**Comment by ognjetina** [comment]
Also I am having problems running this on raspberry pi (first problem is with css loader, for some reason webpack is having an issue with it so I removed css and that module)
But it is also not being able to build the app saying:
Unsupported arch=arm (string): must be a String matching: ia32,x64,arm7I

Do you have any idea why is it not working on raspberry?

**Comment by pbarbiero** [comment]
Are you running `npm run prod` after `npm run build`? 

I cant help as far as raspberry pi, thats electrons end unfortunately.

**Comment by pbarbiero** [comment]
Closing this due to no response. Feel free to respond and I will reopen if necessary.
